[project]
timeout = 30

[[tests]]
name = "fib_rec"
input = ["./$project", "fib_rec", "10"]
expected = """
C: 55
Asm: 55
Emu: 55
"""
rubric = 4

[[tests]]
name = "get_bitseq"
input = ["./$project", "get_bitseq", "94116", "12", "15"]
expected = """
C: 6
Asm: 6
Emu: 6
"""
rubric = 4

[[tests]]
name = "int_to_str"
input = ["./$project", "int_to_str", "255", "-o", "16"]
expected = """
C: 0xff
Asm: 0xff
Emu: 0xff
"""
rubric = 5

[[tests]]
name = "is_pal"
input = ["./$project", "is_pal", "941171149"]
expected = """
C: is a palindrome
Asm: is a palindrome
Emu: is a palindrome
"""
rubric = 4

[[tests]]
name = "max3"
input = ["./$project", "max3", "2", "10", "8"]
expected = """
C: 10
Asm: 10
Emu: 10
"""
rubric = 4

[[tests]]
name = "midpoint"
input = ["./$project", "midpoint", "0", "4"]
expected = """
C: 2
Asm: 2
Emu: 2
"""
rubric = 2

[[tests]]
name = "quadratic"
input = ["./$project", "quadratic", "2", "4", "6", "8"]
expected = """
C: 36
Asm: 36
Emu: 36
"""
rubric = 2

[[tests]]
name = "sort"
input = ["./$project", "sort", "6", "4", "1", "2", "5", "3"]
expected = """
C: 6 5 4 3 2 1
Asm: 6 5 4 3 2 1
Emu: 6 5 4 3 2 1
"""
rubric = 10

[[tests]]
name = "str_to_int"
input = ["./$project", "str_to_int", "0b10000", "-o", "10"]
expected = """
C: 16
Asm: 16
Emu: 16
"""
rubric = 5

[[tests]]
name = "to_upper"
case_sensitive = true
input = ["./$project", "to_upper", "FooBar"]
expected = """
C: FOOBAR
Asm: FOOBAR
Emu: FOOBAR
"""
rubric = 4

[[tests]]
name = "quadratic_analysis"
input = ["./$project", "-a", "quadratic", "2", "4", "6", "8"]
expected = """
C: 36
Asm: 36
Emu: 36
=== Analysis
Instructions Executed  = 6
R-type + I-type        = 5 (83.33%)
Loads                  = 0 (0.00%)
Stores                 = 0 (0.00%)
Jumps/JAL/JALR         = 1 (16.67%)
Conditional branches   = 0 (0.00%)
  Branches taken       = 0 (0.00%)
  Branches not taken   = 0 (0.00%)
"""
rubric = 2

[[tests]]
name = "fib_analysis"
input = ["./$project", "-a", "fib_rec", "10"]
expected = """
C: 55
Asm: 55
Emu: 55
=== Analysis
Instructions Executed  = 1675
R-type + I-type        = 617 (36.84%)
Loads                  = 264 (15.76%)
Stores                 = 264 (15.76%)
Jumps/JAL/JALR         = 353 (21.07%)
Conditional branches   = 177 (10.57%)
  Branches taken       = 88 (49.72%)
  Branches not taken   = 89 (50.28%)
"""
rubric = 2

[[tests]]
name = "str_to_int_dm_32_1"
input = ["./$project", "-dm", "32", "1", "str_to_int", "0xFFFF"]
expected = """
C: 65535
Asm: 65535
Emu: 65535
=== Cache (I)
Type          = direct mapped
Size          = 32 slots
Block size    = 1 words
Ways          = 1
References    = 91
Hits          = 60 (65.93% hit ratio)
Misses        = 31 (34.07% miss ratio)
Misses (cold) = 29
Misses (hot)  = 2
% Used        = 90.62%
"""
rubric = 2

[[tests]]
name = "str_to_int_dm_32_4"
input = ["./$project", "-dm", "32", "4", "str_to_int", "0xFFFF"]
expected = """
C: 65535
Asm: 65535
Emu: 65535
=== Cache (I)
Type          = direct mapped
Size          = 32 slots
Block size    = 4 words
Ways          = 1
References    = 91
Hits          = 82 (90.11% hit ratio)
Misses        = 9 (9.89% miss ratio)
Misses (cold) = 8
Misses (hot)  = 1
% Used        = 25.00%
"""
rubric = 5

[[tests]]
name = "sort_sa_32_1_4"
input = ["./$project", "-sa", "32", "1", "4", "sort", "8", "1", "3", "7", "0", "20", "28", "9"]
expected = """
C: 28 20 9 8 7 3 1 0
Asm: 28 20 9 8 7 3 1 0
Emu: 28 20 9 8 7 3 1 0
=== Cache (I)
Type          = set associative
Size          = 32 slots
Block size    = 1 words
Ways          = 4
References    = 540
Hits          = 258 (47.78% hit ratio)
Misses        = 282 (52.22% miss ratio)
Misses (cold) = 32
Misses (hot)  = 250
% Used        = 100.00%
"""
rubric = 5

[[tests]]
name = "sort_sa_32_4_4"
input = ["./$project", "-sa", "32", "4", "4", "sort", "8", "1", "3", "7", "0", "20", "28", "9"]
expected = """
C: 28 20 9 8 7 3 1 0
Asm: 28 20 9 8 7 3 1 0
Emu: 28 20 9 8 7 3 1 0
=== Cache (I)
Type          = set associative
Size          = 32 slots
Block size    = 4 words
Ways          = 4
References    = 540
Hits          = 441 (81.67% hit ratio)
Misses        = 99 (18.33% miss ratio)
Misses (cold) = 8
Misses (hot)  = 91
% Used        = 25.00%
"""
rubric = 5

[[tests]]
name = "is_pal_analysis_sa_32_4_4"
input = ["./$project", "-a", "-sa", "32", "4", "4", "is_pal", "able was i ere i saw elba"]
expected = """
C: is a palindrome
Asm: is a palindrome
Emu: is a palindrome
=== Analysis
Instructions Executed  = 172
R-type + I-type        = 73 (42.44%)
Loads                  = 36 (20.93%)
Stores                 = 12 (6.98%)
Jumps/JAL/JALR         = 26 (15.12%)
Conditional branches   = 25 (14.53%)
  Branches taken       = 24 (96.00%)
  Branches not taken   = 1 (4.00%)
=== Cache (I)
Type          = set associative
Size          = 32 slots
Block size    = 4 words
Ways          = 4
References    = 172
Hits          = 167 (97.09% hit ratio)
Misses        = 5 (2.91% miss ratio)
Misses (cold) = 5
Misses (hot)  = 0
% Used        = 15.62%
"""
rubric = 5
