
[lab01]

[[lab01.dates]]
suffix = "due"
date = "2026-01-29"
percentage = 1.0

[[lab01.dates]]
suffix = "1week"
date = "2026-02-05"
percentage = 0.75

[[lab01.dates]]
suffix = "super-late"
date = "2026-05-14"
percentage = 0.5

[project01]

[[project01.dates]]
suffix = "due"
date = "2026-02-04"
percentage = 1.0

[[project01.dates]]
suffix = "1week"
date = "2026-02-09"
percentage = 0.75

[[project01.dates]]
suffix = "super-late"
date = "2026-05-14"
percentage = 0.5

[lab02]

[[lab02.dates]]
suffix = "due"
date = "2026-02-10"
percentage = 1.0

[[lab02.dates]]
suffix = "1week"
date = "2026-02-15"
percentage = 0.75

[[lab02.dates]]
suffix = "super-late"
date = "2026-05-14"
percentage = 0.5

[project02]

[[project02.dates]]
suffix = "due"
date = "2026-02-18"
percentage = 1.0

[[project02.dates]]
suffix = "1week"
date = "2026-02-23"
percentage = 0.75

[[project02.dates]]
suffix = "super-late"
date = "2026-05-14"
percentage = 0.5

[lab03]

[[lab03.dates]]
suffix = "due"
date = "2026-02-24"
percentage = 1.0

[[lab03.dates]]
suffix = "1week"
date = "2026-03-01"
percentage = 0.75

[[lab03.dates]]
suffix = "super-late"
date = "2026-05-14"
percentage = 0.5

[project03]

[[project03.dates]]
suffix = "due"
date = "2026-03-03"
percentage = 1.0

[[project03.dates]]
suffix = "1week"
date = "2026-03-08"
percentage = 0.75

[[project03.dates]]
suffix = "super-late"
date = "2026-05-14"
percentage = 0.5

